"""empty message

Revision ID: 66b146b88dff
Revises: c9b667d19b32
Create Date: 2025-03-13 17:32:16.534184

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66b146b88dff'
down_revision: Union[str, None] = 'c9b667d19b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_image_uploads',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('image_link', sa.String(length=255), nullable=False),
                    sa.Column('announcement_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_image_uploads')
    # ### end Alembic commands ###
