"""empty message

Revision ID: c9b667d19b32
Revises: 
Create Date: 2025-03-05 14:37:50.361575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b667d19b32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(192), nullable=False),
    sa.Column('description', sa.String(2040), nullable=False),
    sa.Column('number', sa.String(24), nullable=False),
    sa.Column('owner', sa.String(64), nullable=True),
    sa.Column('terms', sa.String(64), nullable=True),
    sa.Column('contact', sa.String(64), nullable=True),
    sa.Column('due_amount', sa.Integer(), nullable=False),
    sa.Column('wilaya', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(255), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements_business_lines_association',
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('business_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['business_line_id'], ['business_lines.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'business_line_id')
    )
    op.create_table('announcements_types_association',
    sa.Column('announcement_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['announcement_types.id'], ),
    sa.PrimaryKeyConstraint('announcement_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements_types_association')
    op.drop_table('announcements_business_lines_association')
    op.drop_table('announcement_images')
    op.drop_table('business_lines')
    op.drop_table('announcements')
    op.drop_table('announcement_types')
    # ### end Alembic commands ###
